param(
    [Parameter(Mandatory = $true)]
    [string]$Out
)

$ErrorActionPreference = 'Stop'

try {
    $version = (& git rev-parse HEAD 2>$null).Trim()
    if (-not $version) {
        $version = 'unknown'
    } else {
        & git diff-index --quiet HEAD -- 2>$null
        if ($LASTEXITCODE -ne 0) {
            $version = "$version-dirty"
        }
    }
} catch {
    $version = 'unknown'
}

$version = $version.Replace('\', '\\').Replace('"', '\"')
$content = @"
/*  Generated by gen_version_info.ps1  */

#ifndef BAZEL_AUTO_GENERATED_VERSION_INFO_H_
#define BAZEL_AUTO_GENERATED_VERSION_INFO_H_

#include <string>
const std::string GIT_VERSION = "$version";

#endif  // BAZEL_AUTO_GENERATED_VERSION_INFO_H_
"@

$parent = Split-Path -Parent $Out
if ($parent) {
    New-Item -ItemType Directory -Force -Path $parent | Out-Null
}
Set-Content -LiteralPath $Out -Value $content -Encoding ASCII
