load("@cc_toolchains//toolchain:cc_toolchains_setup.bzl", "cc_toolchains_setup")

def cc_toolchains_register():
    cc_toolchains_setup(
        name = "cc_toolchains_setup",
        toolchains = {
            "x86_64": {
                "linux": [
                    {
                        "vendor": "generic",
                        "libc": "glibc",
                        "compiler": "clang",
                        "triple": "x86_64-unknown-linux-gnu",
                        "url": "https://rgit.xiedeacc.com/files/clang22.1.2-linux-x86_64_toolchain.tar.gz",
                        "strip_prefix": "clang22.1.2-linux-x86_64_toolchain",
                        "sha256sum": "e23983e31c234fb1a0095d338021557f101670d3b28a362d1c7efde68dd70206",
                        "sysroot": "@@+http_archive+linux-x86_64-gnu_sysroot//:BUILD.bazel",
                        "sysroot_files": "@@+http_archive+linux-x86_64-gnu_sysroot//:files",
                        "runtime": "@@+http_archive+clang22.1.2-linux-x86_64-gnu_runtime//:BUILD.bazel",
                        "runtime_files": "@@+http_archive+clang22.1.2-linux-x86_64-gnu_runtime//:files",
                        "runtime_resource_directory": "lib/clang/22",
                        "tool_names": {
                            "ar": "llvm-ar",
                            "as": "llvm-as",
                            "c++": "clang++",
                            "cpp": "clang-cpp",
                            "g++": "clang++",
                            "gcc": "clang",
                            "gcov": "llvm-cov",
                            "ld": "ld.lld",
                            "llvm-cov": "llvm-cov",
                            "nm": "llvm-nm",
                            "objcopy": "llvm-objcopy",
                            "objdump": "llvm-objdump",
                            "strip": "llvm-strip",
                        },
                        "cxx_builtin_include_directories": [
                            "lib/clang/22/include",
                        ],
                        "sysroot_include_directories": [
                            "usr/include",
                        ],
                        "runtime_include_directories": [
                            "include/c++/v1",
                        ],
                        "sysroot_lib_directories": [
                            "lib",
                            "usr/lib",
                            "lib64",
                            "usr/lib64",
                        ],
                        "runtime_lib_directories": [
                            "lib",
                        ],
                        "link_libs": [],
                        "supports_start_end_lib": True,
                        "debug": True,
                    },
                    {
                        "vendor": "generic",
                        "libc": "musl",
                        "compiler": "clang",
                        "triple": "x86_64-unknown-linux-musl",
                        "url": "https://rgit.xiedeacc.com/files/clang22.1.2-linux-x86_64_toolchain.tar.gz",
                        "strip_prefix": "clang22.1.2-linux-x86_64_toolchain",
                        "sha256sum": "e23983e31c234fb1a0095d338021557f101670d3b28a362d1c7efde68dd70206",
                        "sysroot": "@@+http_archive+linux-x86_64-musl_sysroot//:BUILD.bazel",
                        "sysroot_files": "@@+http_archive+linux-x86_64-musl_sysroot//:files",
                        "runtime": "@@+http_archive+clang22.1.2-linux-x86_64-musl_runtime//:BUILD.bazel",
                        "runtime_files": "@@+http_archive+clang22.1.2-linux-x86_64-musl_runtime//:files",
                        "runtime_resource_directory": "lib/clang/22",
                        "tool_names": {
                            "ar": "llvm-ar",
                            "as": "llvm-as",
                            "c++": "clang++",
                            "cpp": "clang-cpp",
                            "g++": "clang++",
                            "gcc": "clang",
                            "gcov": "llvm-cov",
                            "ld": "ld.lld",
                            "llvm-cov": "llvm-cov",
                            "nm": "llvm-nm",
                            "objcopy": "llvm-objcopy",
                            "objdump": "llvm-objdump",
                            "strip": "llvm-strip",
                        },
                        "cxx_builtin_include_directories": [
                            "lib/clang/22/include",
                        ],
                        "sysroot_include_directories": [
                            "usr/include",
                        ],
                        "runtime_include_directories": [
                            "include/c++/v1",
                        ],
                        "sysroot_lib_directories": [
                            "usr/lib",
                            "lib",
                        ],
                        "runtime_lib_directories": [
                            "lib",
                        ],
                        "link_libs": [],
                        "supports_start_end_lib": True,
                        "debug": True,
                    },
                ],
                "osx": [
                    {
                        "vendor": "generic",
                        "libc": "macosx",
                        "compiler": "clang",
                        "triple": "x86_64-apple-darwin",
                        "url": "https://rgit.xiedeacc.com/files/clang18.1.8-linux-x86_64_toolchain.tar.gz",
                        "strip_prefix": "clang18.1.8-linux-x86_64_toolchain",
                        "sha256sum": "be64a29251dd2b7ae6e8e783f99ab395b4bf2a75f98d8a6e03bf855e9d811434",
                        "sysroot": "@@+http_archive+macosx14.2-x86_64_sysroot//:BUILD.bazel",
                        "tool_names": {
                            "ar": "x86_64-apple-darwin23.3-libtool",
                            "as": "x86_64-apple-darwin23.3-as",
                            "c++": "clang++",
                            "cpp": "clang-cpp",
                            "g++": "clang++",
                            "gcc": "clang",
                            "gcov": "x86_64-apple-darwin23.3-gcov",
                            "ld": "ld64",
                            "llvm-cov": "None",
                            "nm": "x86_64-apple-darwin23.3-nm",
                            "objcopy": "x86_64-apple-darwin-objcopy",
                            "objdump": "x86_64-apple-darwin-objdump",
                            "strip": "x86_64-apple-darwin23.3-strip",
                        },
                        "cxx_builtin_include_directories": [
                        ],
                        "lib_directories": [
                        ],
                        "sysroot_include_directories": [
                            "llvm18.1.8/include/c++/v1",
                            "llvm18.1.8/lib/clang/18/include",
                            "usr/include",
                            "System/Library/Frameworks",
                        ],
                        "sysroot_lib_directories": [
                            "llvm18.1.8/lib",
                            "llvm18.1.8/lib/clang/18/lib/darwin",
                            "usr/lib",
                        ],
                        "link_libs": [
                            "libclang_rt.osx.a",
                        ],
                        "supports_start_end_lib": False,
                        "debug": True,
                    },
                ],
            },
            "aarch64": {
                "linux": [
                    {
                        "vendor": "generic",
                        "libc": "glibc",
                        "compiler": "clang",
                        "triple": "aarch64-unknown-linux-gnu",
                        "url": "https://rgit.xiedeacc.com/files/clang22.1.2-linux-x86_64_toolchain.tar.gz",
                        "strip_prefix": "clang22.1.2-linux-x86_64_toolchain",
                        "sha256sum": "e23983e31c234fb1a0095d338021557f101670d3b28a362d1c7efde68dd70206",
                        "sysroot": "@@+http_archive+linux-aarch64-gnu_sysroot//:BUILD.bazel",
                        "sysroot_files": "@@+http_archive+linux-aarch64-gnu_sysroot//:files",
                        "runtime": "@@+http_archive+clang22.1.2-linux-aarch64-gnu_runtime//:BUILD.bazel",
                        "runtime_files": "@@+http_archive+clang22.1.2-linux-aarch64-gnu_runtime//:files",
                        "runtime_resource_directory": "lib/clang/22",
                        "tool_names": {
                            "ar": "llvm-ar",
                            "as": "llvm-as",
                            "c++": "clang++",
                            "cpp": "clang-cpp",
                            "g++": "clang++",
                            "gcc": "clang",
                            "gcov": "llvm-cov",
                            "ld": "ld",
                            "llvm-cov": "llvm-cov",
                            "nm": "llvm-nm",
                            "objcopy": "llvm-objcopy",
                            "objdump": "llvm-objdump",
                            "strip": "llvm-strip",
                        },
                        "cxx_builtin_include_directories": [
                            "lib/clang/22/include",
                        ],
                        "sysroot_include_directories": [
                            "usr/include",
                        ],
                        "runtime_include_directories": [
                            "include/c++/v1",
                        ],
                        "sysroot_lib_directories": [
                            "lib",
                            "usr/lib",
                            "lib64",
                            "usr/lib64",
                        ],
                        "runtime_lib_directories": [
                            "lib",
                        ],
                        "link_libs": [],
                        "supports_start_end_lib": True,
                        "debug": True,
                    },
                    {
                        "vendor": "generic",
                        "libc": "glibc",
                        "compiler": "gcc",
                        "triple": "aarch64-linux-gnu",
                        "url": "https://rgit.xiedeacc.com/files/gcc16.1.0-aarch64-linux-gnu_toolchain.tar.gz",
                        "strip_prefix": "gcc16.1.0-aarch64-linux-gnu_toolchain",
                        "sha256sum": "a6e29b15095e0b6236151fe0e9c9fbc1f3453673620cf7a911bd52393a5d86b4",
                        "sysroot": "@@+http_archive+linux-aarch64-gnu_sysroot//:BUILD.bazel",
                        "sysroot_files": "@@+http_archive+linux-aarch64-gnu_sysroot//:files",
                        "runtime": "@@+http_archive+gcc16.1.0-linux-aarch64-gnu_runtime//:BUILD.bazel",
                        "runtime_files": "@@+http_archive+gcc16.1.0-linux-aarch64-gnu_runtime//:files",
                        "tool_names": {
                            "ar": "aarch64-linux-gnu-ar",
                            "as": "aarch64-linux-gnu-as",
                            "c++": "aarch64-linux-gnu-c++",
                            "cpp": "aarch64-linux-gnu-cpp",
                            "g++": "aarch64-linux-gnu-g++",
                            "gcc": "aarch64-linux-gnu-gcc",
                            "gcov": "aarch64-linux-gnu-gcov",
                            "ld": "aarch64-linux-gnu-ld",
                            "llvm-cov": "aarch64-linux-gnu-gcov",
                            "nm": "aarch64-linux-gnu-nm",
                            "objcopy": "aarch64-linux-gnu-objcopy",
                            "objdump": "aarch64-linux-gnu-objdump",
                            "strip": "aarch64-linux-gnu-strip",
                        },
                        "cxx_builtin_include_directories": [
                            "lib/gcc/aarch64-linux-gnu/16.1.0/include",
                            "lib/gcc/aarch64-linux-gnu/16.1.0/include-fixed",
                        ],
                        "sysroot_include_directories": [
                            "usr/include",
                        ],
                        "runtime_include_directories": [
                            "include/c++/16.1.0/aarch64-linux-gnu",
                            "include/c++/16.1.0",
                            "include/c++/16.1.0/backward",
                        ],
                        "sysroot_lib_directories": [
                            "lib",
                            "usr/lib",
                            "lib64",
                            "usr/lib64",
                        ],
                        "runtime_lib_directories": [
                            "lib/gcc/aarch64-linux-gnu/16.1.0",
                            "lib/aarch64-linux-gnu",
                        ],
                        "link_libs": [],
                        "supports_start_end_lib": False,
                        "debug": True,
                    },
                    {
                        "vendor": "generic",
                        "libc": "musl",
                        "compiler": "gcc",
                        "triple": "aarch64-unknown-linux-musl",
                        "url": "https://rgit.xiedeacc.com/files/gcc16.1.0-aarch64-unknown-linux-musl_toolchain.tar.gz",
                        "strip_prefix": "gcc16.1.0-aarch64-unknown-linux-musl_toolchain",
                        "sha256sum": "602f2cf24e552756597f2469febc3e1086d36a46cc1f0239e34b846f1800fd01",
                        "sysroot": "@@+http_archive+linux-aarch64-musl_sysroot//:BUILD.bazel",
                        "sysroot_files": "@@+http_archive+linux-aarch64-musl_sysroot//:files",
                        "runtime": "@@+http_archive+gcc16.1.0-linux-aarch64-musl_runtime//:BUILD.bazel",
                        "runtime_files": "@@+http_archive+gcc16.1.0-linux-aarch64-musl_runtime//:files",
                        "tool_names": {
                            "ar": "aarch64-unknown-linux-musl-ar",
                            "as": "aarch64-unknown-linux-musl-as",
                            "c++": "aarch64-unknown-linux-musl-c++",
                            "cpp": "aarch64-unknown-linux-musl-cpp",
                            "g++": "aarch64-unknown-linux-musl-g++",
                            "gcc": "aarch64-unknown-linux-musl-gcc",
                            "gcov": "aarch64-unknown-linux-musl-gcov",
                            "ld": "aarch64-unknown-linux-musl-ld",
                            "llvm-cov": "aarch64-unknown-linux-musl-gcov",
                            "nm": "aarch64-unknown-linux-musl-nm",
                            "objcopy": "aarch64-unknown-linux-musl-objcopy",
                            "objdump": "aarch64-unknown-linux-musl-objdump",
                            "strip": "aarch64-unknown-linux-musl-strip",
                        },
                        "cxx_builtin_include_directories": [
                            "lib/gcc/aarch64-unknown-linux-musl/16.1.0/include",
                            "lib/gcc/aarch64-unknown-linux-musl/16.1.0/include-fixed",
                        ],
                        "sysroot_include_directories": [
                            "usr/include",
                        ],
                        "runtime_include_directories": [
                            "include/c++/16.1.0/aarch64-unknown-linux-musl",
                            "include/c++/16.1.0",
                            "include/c++/16.1.0/backward",
                        ],
                        "sysroot_lib_directories": [
                            "lib",
                            "usr/lib",
                        ],
                        "runtime_lib_directories": [
                            "lib/gcc/aarch64-unknown-linux-musl/16.1.0",
                            "lib/aarch64-unknown-linux-musl",
                        ],
                        "link_libs": [],
                        "supports_start_end_lib": False,
                        "debug": True,
                    },
                    {
                        "vendor": "generic",
                        "libc": "musl",
                        "compiler": "clang",
                        "triple": "aarch64-unknown-linux-musl",
                        "url": "https://rgit.xiedeacc.com/files/clang22.1.2-linux-x86_64_toolchain.tar.gz",
                        "strip_prefix": "clang22.1.2-linux-x86_64_toolchain",
                        "sha256sum": "e23983e31c234fb1a0095d338021557f101670d3b28a362d1c7efde68dd70206",
                        "sysroot": "@@+http_archive+linux-aarch64-musl_sysroot//:BUILD.bazel",
                        "sysroot_files": "@@+http_archive+linux-aarch64-musl_sysroot//:files",
                        "runtime": "@@+http_archive+clang22.1.2-linux-aarch64-musl_runtime//:BUILD.bazel",
                        "runtime_files": "@@+http_archive+clang22.1.2-linux-aarch64-musl_runtime//:files",
                        "runtime_resource_directory": "lib/clang/22",
                        "tool_names": {
                            "ar": "llvm-ar",
                            "as": "llvm-as",
                            "c++": "clang++",
                            "cpp": "clang-cpp",
                            "g++": "clang++",
                            "gcc": "clang",
                            "gcov": "llvm-cov",
                            "ld": "ld.lld",
                            "llvm-cov": "llvm-cov",
                            "nm": "llvm-nm",
                            "objcopy": "llvm-objcopy",
                            "objdump": "llvm-objdump",
                            "strip": "llvm-strip",
                        },
                        "cxx_builtin_include_directories": [
                            "lib/clang/22/include",
                        ],
                        "sysroot_include_directories": [
                            "usr/include",
                        ],
                        "runtime_include_directories": [
                            "include/c++/v1",
                        ],
                        "sysroot_lib_directories": [
                            "lib",
                            "usr/lib",
                        ],
                        "runtime_lib_directories": [
                            "lib",
                        ],
                        "link_libs": [],
                        "supports_start_end_lib": True,
                        "debug": True,
                    },
                ],
            },
        },
    )
