set -x
clear && bazel test --config=cpplint //...
clear && bazel test --config=unit_test //...
clear && bazel test --config=sanitize //...
clear && bazel test --config=gcc --config=unit_test_tcmalloc //...
clear && bazel test --config=gcc --config=unit_test_jemalloc //...
clear && bazel test --config=gcc --config=sanitize //src/util/...
clear && bazel test --config=clang --config=unit_test_tcmalloc //...
clear && bazel test --config=clang --config=unit_test_jemalloc //...
clear && bazel test --config=clang --config=sanitize //...

clear && bazel build --config=gcc_macosx_x86_64 //...
clear && bazel build --config=openwrt_aarch64 //...
clear && bazel build --config=clang_aarch64 //...
clear && bazel build --config=clang_macosx_x86_64 //...

clear && bazel coverage //...
