// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/proto/error.proto
// Protobuf C++ Version: 5.27.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_src_2fproto_2ferror_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_src_2fproto_2ferror_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_src_2fproto_2ferror_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_src_2fproto_2ferror_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_src_2fproto_2ferror_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace bazel_template {
namespace proto {
enum ErrCode : int {
  SUCCESS = 0,
  FAST_FAIL = 1,
  FAIL = 2,
  ErrCode_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ErrCode_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ErrCode_IsValid(int value);
extern const uint32_t ErrCode_internal_data_[];
constexpr ErrCode ErrCode_MIN = static_cast<ErrCode>(0);
constexpr ErrCode ErrCode_MAX = static_cast<ErrCode>(2);
constexpr int ErrCode_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
ErrCode_descriptor();
template <typename T>
const std::string& ErrCode_Name(T value) {
  static_assert(std::is_same<T, ErrCode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ErrCode_Name().");
  return ErrCode_Name(static_cast<ErrCode>(value));
}
template <>
inline const std::string& ErrCode_Name(ErrCode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ErrCode_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool ErrCode_Parse(absl::string_view name, ErrCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ErrCode>(
      ErrCode_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace bazel_template


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::bazel_template::proto::ErrCode> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::bazel_template::proto::ErrCode>() {
  return ::bazel_template::proto::ErrCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_src_2fproto_2ferror_2eproto_2epb_2eh
